debug:
  false
server:
  port: 8888
  servlet:
    context-path: /sso
spring:
  profiles:
    active: @profileActive@
  devtools:
    restart:
      enabled: true #设置开启热部署
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  datasource:       #多数据源配置
    druid:
      oracle-db:
        username: ${config.oracle_jdbc_username}
        password: ${config.oracle_jdbc_password}
        #        driver-class-name: oracle.jdbc.OracleDriver
        driver-class-name: com.mysql.jdbc.Driver
        url: ${config.oracle_jdbc_url}
        initialSize: 2
        minIdle: 2
        maxActive: 20
      mysql-db:
        username: ${config.mysql_jdbc_username}
        password: ${config.mysql_jdbc_password}
        driver-class-name: com.mysql.jdbc.Driver
        url: ${config.mysql_jdbc_url}
        initialSize: 3
        minIdle: 3
        maxActive: 30
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/hrb/sso/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/hrb/sso/*/dao/*Dao.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hrb.sso.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 4
    logic-not-delete-value: 0
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须
    jdbc-type-for-null: 'null'
