spring:
  profiles.active: @profileActive@
  devtools.restart.enabled: true #设置开启热部署
  freemarker.cache: false    #页面不加载缓存，修改即时生效
  main.allow-bean-definition-overriding: true
  datasource.type: com.alibaba.druid.pool.DruidDataSource #多数据源

# 引入日志配置文件
logging.config: classpath:logback.xml

# redis配置
redis:
  cluster:
    # redis-server默认从zk上读取，zk取不到，才用此此值
    redis-server: 127.0.0.1:6379
    connection-timeout: 2000
    so-timeout: 3000
    max-redirections: 5

# 数据源配置
datasource:
  oracle-db:
    url: ${config.oracle_jdbc_url}
    username: ${config.oracle_jdbc_username}
    password: ${config.oracle_jdbc_password}
    driver-class-name: oracle.jdbc.OracleDriver
    # driver-class-name: com.mysql.jdbc.Driver
    initialSize: 2
    minIdle: 2
    maxActive: 20
  mysql-db:
    url: ${config.mysql_jdbc_url}
    username: ${config.mysql_jdbc_username}
    password: ${config.mysql_jdbc_password}
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 3
    minIdle: 3
    maxActive: 30

# Mybatis-plus配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/hurbao/sso/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/hurbao/*/*/dao/*Dao.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hurbao.sso.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      # 是否开启大写命名，默认不开启
      capital-mode: false
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #逻辑已删除值(逻辑删除下有效)
      logic-delete-value: 1
      #逻辑未删除值(逻辑删除下有效)
      logic-not-delete-value: 0
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射  A_COLUMN->aColumn
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须
    jdbc-type-for-null: 'null'
