spring:
  profiles.active: @profileActive@
  devtools.restart.enabled: true #设置开启热部署
  freemarker.cache: false    #页面不加载缓存，修改即时生效
  main.allow-bean-definition-overriding: true
  datasource.type: com.alibaba.druid.pool.DruidDataSource #多数据源


# 引入日志配置文件
logging.config: classpath:logback.xml


# redis配置
redis:
  cluster:
    connection-timeout: 2000
    so-timeout: 3000
    max-redirections: 5



# 数据源配置
datasource:
  oracle-db:
    initialSize: 2
    minIdle: 2
    maxActive: 20
    # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
    # 借出连接时不要测试，否则很影响性能
    testOnBorrow: false
    # 验证连接是否可用，使用的SQL语句
    validationQuery: 'select 1 from dual'
  mysql-db:
    initialSize: 3
    minIdle: 3
    maxActive: 30
    # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
    # 借出连接时不要测试，否则很影响性能
    testOnBorrow: false
    # 验证连接是否可用，使用的SQL语句
    validationQuery: 'select 1'


# Mybatis-plus配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/hurbao/sso/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/com/hurbao/*/*/dao/*Dao.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hurbao.sso.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      # 是否开启大写命名，默认不开启
      capital-mode: false
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #逻辑已删除值(逻辑删除下有效)
      logic-delete-value: 1
      #逻辑未删除值(逻辑删除下有效)
      logic-not-delete-value: 0
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射  A_COLUMN->aColumn
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须
    jdbc-type-for-null: 'null'
